### ISSUE TITLE
Install/run as flatpak fails because of webkit2gtk-5.0 dependency not found

### ISSUE THREAD

**Issue by baumkuchen42** [Blquinn/notes#14]
First of all: I really love your application and use it regularly! So far, it's also been pretty stable, save for a few times where my mouse cursor stopped working but that might also be an issue not directly connected to the application and worked again after a restart.

I installed it as a flatpak via gnome-builder. Unfortunately, I cannot start the flatpak anymore because it cannot find the library `libwebkit2gtk-5.0.so.0`.

On building it with meson in gnome-builder, it results in:

```sh
../src/meson.build:21:0: ERROR: Dependency "webkit2gtk-5.0" not found, tried pkgconfig and cmake
```

I have the nightly gnome runtimes for gnome 42, 43 and also older ones installed. Using Fedora 37.

The only thing I found on the internet that might be related to the cause of this is: https://discourse.gnome.org/t/webkitgtk-for-gtk-4-status-update-and-api-changes/11033/2

**Comment by blquinn** [comment]
Glad to hear you're getting use out of the app :)

I believe the cursor freezing is due to a bug with webkit. There's a bunch of bugs for gtk4 on their bug tracker still, it's kind of prerelease software at the moment.

It seems that webkit2gtk-5.0 is now missing from the gnome master flatpak and it's been replaced by webkitgtk-6.0, which I didn't know existed.

Try pulling master and giving it another shot.

**Comment by blquinn** [comment]
I played around with the app for a few minutes after I updated the webkit version... I didn't experience any hanging / freezing, so I'm hoping that means that they fixed some stuff in the new version.

Let me know if that's resolved for you as well. I want to release it onto flathub if the issue is resolved.

Thanks!

**Comment by baumkuchen42** [comment]
Sorry for the lack of feedback on this! I haven't had the time to actually use the app for longer periods of time. The issue didn't appear in the short usage time at least.

However there is a new issue now, which seems to be related to this one (but I can open a new issue if you'd like that better).

The app doesn't start anymore and when I try to rebuild, it fails with that error:

```bash
../src/widgets/editor.vala:114:40-114:62: error: The type name `WebKit.JavascriptResult' could not be found
  114 |         private void on_editor_changed(WebKit.JavascriptResult payload) {
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~           
../src/widgets/editor.vala:382:57-382:79: error: The type name `WebKit.JavascriptResult' could not be found
  382 |         public void on_editor_active_attributes_changed(WebKit.JavascriptResult payload) {
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~~           
Compilation failed: 2 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.
Error: module notes: Child process exited with code 1
```

**Comment by blquinn** [comment]
Yea I was just looking into this yesterday actually.

I have to upgrade webkitgtk to version 6.0 in order to get it to work properly with gtk4.. I think webkitgtk-5.0 was not ever going to be a real stable release so its kind of defunct from what I can tell (Unfortunate reality of working with bleeding edge software). Unfortunately docs aren't great for webkitgtk-6.0 so it wasn't as easy as I thought. Specifically I am using a method `WebView.run_javascript()` currently, which no longer exists. I wasn't able to find a workaround in the 30 minutes or so I was digging into it. I'm sure I'll figure it out eventually.

**Comment by blquinn** [comment]
I've fixed this, however the webview now doesn't render on the current flatpak version of webkitgtk-6.0.

Maybe you'll have better luck?

**Comment by baumkuchen42** [comment]
It installs and runs now, thank you very much!
